version: '3.8'

services:
  server:
    build:
      context: .
    command: npm run start-server
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - "./../local_data_copy:/app/data"
  jobs_worker:
    build:
      context: .
    command: npm run start-jobs-worker
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - UNSPLASH_ACCESS_TOKEN=${UNSPLASH_ACCESS_TOKEN}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - "./../local_data_copy:/app/data"
  redis:
    image: "redis"
    ports:
      - "6379:6379"